CREATE TABLE IF NOT EXISTS thread (
  thread_id BIGINT AUTO_INCREMENT,
  title VARCHAR(25) NOT NULL,
  author_id BIGINT NOT NULL,
  comment_count INT NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (thread_id)
)
ENGINE = INNODB,
CHARACTER SET = utf8mb4,
COLLATE utf8mb4_general_ci;